version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: octopod-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - octopod-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: octopod-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=octopod
      - DB_SYNC=true
    depends_on:
      - postgres
    networks:
      - octopod-network

  postgres:
    image: postgres:15-alpine
    container_name: octopod-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=octopod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - octopod-network

networks:
  octopod-network:
    driver: bridge

volumes:
  postgres_data:
